spring.application.name=SMMDS

spring.datasource.url=jdbc:postgresql://dpg-d9741s6q1p3s738cbj70-a.oregon-postgres.render.com/projeto_integrador_m7vk?sslmode=require
spring.datasource.username=projeto_integrador_e1ww_user
spring.datasource.password=MRrWKPizQFouJ2jMuinj0UfYJDx4pGfj
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama3-8b-8192
